napari-threedee/napari-threedee

- examples/rendering_plane.py
- examples/rendering_plane_widget.py
- src/napari_threedee/_dock_widget.py
- src/napari_threedee/annotators/plane_point_annotator.py
- src/napari_threedee/annotators/qt_plane_point_annotator.py
- src/napari_threedee/base.py
- src/napari_threedee/manipulators/base_manipulator.py
- src/napari_threedee/manipulators/point_manipulator.py
- src/napari_threedee/manipulators/qt_render_plane_manipulator.py
- src/napari_threedee/manipulators/render_plane_manipulator.py
- src/napari_threedee/utils/napari_utils.py
Sorry for the large PR, this includes
- a base model `ThreeDeeModel` for all manipulator/annotator objects in napari-threedee
- a widget which can autogenerate GUI elements from a given `ThreeDeeModel` class
- example implementation of a `PlanePointAnnotator` using this API
- refactor `BaseManipulator` to follow this API
- set initial rotator normals for all rotators in `RenderingPlaneManipulator`
Refactoring the `BaseManipulator` mainly involved making it so we can switch layers in and out. Autogeneration of GUIs doesn't work for manipulators yet because our manipulators don't gracefully handle the `layer=None` case
There is also a bug which appears if the initial rotators don't align with the initial rotation matrix (`np.eye(3)`) - I've changed the render plane example to highlight …
> `ThreedeeModel` and `QtThreeDeeWidgetBase`

- .github/workflows/build-and-deploy-docs.yml
this PR adds an initial github actions to build and deploy the docs. this should host the docs at `napari-threedee.github.io/napari-threedee`. Will attempt to deploy to the base `napari-threedee.github.io` in a follow up PR.
> add gh actions

- .github/workflows/test-docs-pr.yml
This PR adds a github actions workflow that builds the docs on PR.
closes #53
> add CI docs build test for PRs

- README.md
switch the link URLs in the readme badge to napari-threedee/napari-threedee
> fix links in readme badges

- .github/workflows/build-and-deploy-docs.yml
- .github/workflows/test-docs-pr.yml
- docs/getting_started/developers.md
- docs/getting_started/users.md
- docs/how_to/how_to.md
- docs/how_to/how_to_render_plane_manipulator.md
- docs/index.md
- mkdocs.yml
- setup.cfg
- src/napari_threedee/utils/napari_utils.py
This PR updates the landing page of the docs:
- add video
- add installation instructions
- add getting started section and stubs for the getting started pages
> update overview docs page and add stubs for getting started

- src/napari_threedee/annotators/sphere_annotator.py
- src/napari_threedee/annotators/spline_annotator.py
- src/napari_threedee/annotators/surface_annotator.py
- src/napari_threedee/visualization/camera_spline.py
this is useful when reusing annotators but replacing data/layers for different datasets
cc @kevinyamauchi
> override keybindings by default

- mkdocs.yml
I'd like to propose automatically looping videos in the napari-threedee docs (until the user clicks to stop it).
The [render plane manipulator docs page](https://napari-threedee.github.io/how_to/render_plane_manipulator/) includes a 4 second video. Others are a little longer (eg: the main page video is 15 seconds long), but it's easy to miss, especially when you're also trying to read the text paragraphs as well.
> Enable video looping in docs pages

- src/napari_threedee/geometry_utils.py
- src/napari_threedee/manipulators/layer_manipulator.py
- src/napari_threedee/utils/napari_utils.py
- src/napari_threedee/visualization/_qt/qt_lighting_control.py
- src/napari_threedee/visualization/_tests/test_camera_spline.py
- src/napari_threedee/visualization/_tests/test_lighting_control.py
- src/napari_threedee/visualization/lighting_control.py
First of all - this plugin is awesome! I was down the path of changing lighting myself and was very to happy to find this plugin to solve the problem for me.
I am running napari from `main` - I got this error when trying to use the mesh lighting controls:
```
File ~/mf/envs/napari/lib/python3.10/site-packages/napari_threedee/visualization/lighting_control.py:55, in LightingControl._on_camera_change(self=<napari_threedee.visualization.lighting_control.LightingControl object>, event=<Event blocked=False handled=False native=None source=None sources=[] type='angles'>)
52 view_direction = np.asarray(self._viewer.camera.view_direction)
54 for layer, visual in zip(self.selected_layers, self.selected_layer_visuals):
---> 55     dims_displayed = layer._dims_displayed
layer = <Surface layer …
```
> Fix for layer._dims_displayed removal in napari and update lighting control widget

- examples/library/mesh_headlight.py
- examples/plugin/mesh_headlight.py
The nilearn library is not compatible with numpy > 1.24, so I am swapping out the mesh in the `mesh_headlight.py` example for the triceratops from vispy.
closes #103 cc @GenevieveBuckley
> swap example mesh

- docs/examples/plugin/spline_annotator_plugin.py
- src/napari_threedee/annotators/_tests/test_spline_annotator.py
- src/napari_threedee/annotators/paths/annotator.py
- src/napari_threedee/data_models/paths.py
This closes #129 . I added a class method that initializes the PathAnnotator points layer for a given ndim. I also added a read-only `PathAnnotator.active_path_id` property (just returns the current_properties value from the points layer) since I this is useful information to be able to easily get.
> Fix empty PathAnnotator points layer for ndim > 3

- setup.cfg
`mkdocs-gallery` was updated so we no longer need to pin `mkdocs`
closes #113
> update mkdocs versions

- .github/workflows/test_and_deploy.yml
current tests are failing to render the examples due to openGL error. I think this is because of the recent PyOpenGL release (3.1.7)
> pin PyOpenGL for rendering on docs

- src/napari_threedee/napari.yaml
Hi folks, I noticed you had `visibility: 'hidden'` set in your napari hub config. I'm in the process of updating the napari hub to use the `visibility` flag in the manifest, so I've added this flag there as well. 
The napari hub changes aren't released yet, but this will be a hard deprecation of the flag in its current location, so I've not yet removed it from `.napari-hub/config.yml`. This way we don't risk your plugin accidentally being visible while we switch over to the manifest flag. 
Once changes to the napari hub are all released I'll make a follow up PR to remove the unused file. Let me know if there's any issues 😊
> Add `visibility` flag to manifest

- src/napari_threedee/_backend/threedee_widget_base.py
When using pyside2 napari backend, napari-threedee widgets don't work with:
```
RuntimeError: Failed to import command at 'napari_threedee.dock_widgets:QtPointAnnotatorWidget': No module named 'PyQt5'
```
In this PR, the hard-coded import from PyQt5 is changed to qtpy, see also:
https://napari.org/stable/plugins/best_practices.html#don-t-include-pyside2-or-pyqt5-in-your-plugin-s-dependencies
> import from qtpy not PyQt5

- .github/workflows/test_and_deploy.yml
- docs/getting_started/developers.md
- mkdocs.yml
In this PR, I fix the deprecated and/or changed mkdocs settings.
Edit: I added uploading the docs artifact to the workflow step, so I could see that the docs look correct, with the few emoji, etc.
Edit2: While I was at it, I fixed the broken links here:
https://napari-threedee.github.io/getting_started/developers/
> [Maint] Fix the error in CI relating to docs building.

- src/napari_threedee/visualization/camera_spline.py
Closes https://github.com/napari-threedee/napari-threedee/issues/146
So I think this was simply missed in the refactoring of https://github.com/napari-threedee/napari-threedee/pull/96
The `set from current view` button was still referencing code that had been removed.
In this PR, I remove the old PathAnnotator code and use SplineSampler, analogous to the code used further down, in `set_camera_position`.
As far as I can tell this is working correctly, when comparing this branch vs. 1aa50dd which was before the refactor.
> [Bugfix] Use SplineSampler instead of PathAnnotator for `set_view_button` of spline_camera

- docs/getting_started/developers.md
- docs/index.md
Closes: https://github.com/napari-threedee/napari-threedee/issues/156
Fixes the broken links by linking to the markdown properly.
Also noticed a typo in the index, so I fixed that too!
> [docs, bugfix] Fix developers getting started broken links

- .github/workflows/test_and_deploy.yml
This PR implements a few small things:
1. it updated the action versions to silence node version warnings
2. adds python 3.10 to the matrix -- this matches tox.ini
3. It sets `fail-fast` to False.
Currently, by default, tests fail-fast, meaning that if one platform fails, everything is canceled.
This could be annoying because there can be an issue specific to a python version or OS. With fail-fast set to false, the whole matrix will run.
4. implements concurrency, so that another push to a branch will cancel tests, rather than piling them up. This can help offset the fail-fast change.
> [Maint] update CI workflow to not fail-fast, use concurrency, and update actions

- .github/workflows/test_and_deploy.yml
- setup.cfg
- src/napari_threedee/annotators/paths/annotator.py
- src/napari_threedee/annotators/paths/constants.py
napari 0.4.19 updated the point coloring API, which broke the path annotator (#158). In short, we were storing numpy arrays in a column of the features table, which tripped up the napari coloring code (thanks for the sleuthing, @psobolewskiPhD !). I've updated it so that we store each element of the RGBA colors as individual columns, which seems to fix the error. (it's probably better practice to not store arrays in the columns anyway 😬 )
Also, this adds the `html_clean` dependency required to do the notebook display used in our docs build: https://github.com/napari/napari/pull/6799 
cc @psobolewskiPhD , @alisterburt
> Fix path annotator color behavior and mkdocs build

- src/napari_threedee/_backend/manipulator/napari_manipulator_backend.py
Closes: https://github.com/napari-threedee/napari-threedee/issues/152
In https://github.com/napari/napari/pull/5701 (released in 0.4.18) the layer property `interactive` was deprecated. This results in a spam of FutureWarnings, which are annoying if using napari-threedee in a notebook.
In this PR, I replace the usage of `layer.interactive` with `layer.mouse_pan`, as instructed by https://github.com/napari/napari/pull/5701
> [bugfix] change layer.interactive to layer.mouse_pan

- src/napari_threedee/_backend/manipulator/vispy_manipulator_visual.py
Closes: https://github.com/napari-threedee/napari-threedee/issues/153
This PR sets the vispy marker symbol for the translator handle to square, to set it off visually from the rotator handles. This way the color coordination is preserved, but there is still a visual difference which makes it easier to explain what does what.
Here's what RenderPlane Manipulator looks like now:
Note I kept the `spherical` because otherwise it looked really wierd without the 3D effect. So it looks a bit wierd, but it does stand out against the other handles.
Open to suggestions for something else. I tried a few of the other symbols and they didn't really work as well as I thought.
> [Enhancement] use symbol square for translator handle

- src/napari_threedee/manipulators/point_manipulator.py
The point manipulator wasn't working because the translation on the manipulator kept getting overwritten during the drag. I chased this down to this layer refresh call: https://github.com/napari-threedee/napari-threedee/blob/ba8a5af163dad60c1e42d34e1c246bdd72fcf208/src/napari_threedee/manipulators/point_manipulator.py#L103
If you replace it with a `layer.events.set_data()` call, the problem persists. That event pretty much only triggers this callback: https://github.com/napari/napari/blob/cf68ee5ffbe6f5ff4861642c759eaff181ef6749/napari/_vispy/layers/points.py#L42-L88
so I think it's something in there (e.g., the `self.reset()`). I think this is caused by the manipulator visual being a child of the layer visual. This might indicate that we want to separate the manipulator and layer …
> fix the point manipulator

- src/napari_threedee/manipulators/render_plane_manipulator.py
Closes: https://github.com/napari-threedee/napari-threedee/issues/164
When I first started using the render plane manipulator I was a bit confused as to the 2 balls.
It's a bit tricky to position the plane how you want because you need to "rotate the manipulator" and then rotate the plane -- even for simple orthogonal rotations.
Here I enable the rotators for all the axes. It's busier, but I i think it's more visually consistent and easier to understand that you can rotate around each axis. For the translator, It does benefit form https://github.com/napari-threedee/napari-threedee/pull/165
to make translator vs. rotator more clear.
Anyhow, here's what it looks like now:
Just throwing this out.
> [Enhancement] enable all the rotators for render plane manipulator

- src/napari_threedee/_backend/manipulator/drag_managers.py
- src/napari_threedee/_backend/manipulator/napari_manipulator_backend.py
- src/napari_threedee/manipulators/base_manipulator.py
- src/napari_threedee/manipulators/layer_manipulator.py
- src/napari_threedee/manipulators/point_manipulator.py
- src/napari_threedee/manipulators/render_plane_manipulator.py
- src/napari_threedee/utils/napari_utils.py
As discussed in #163 , switching the manipulators to world coordinates may be beneficial for keeping the size correct when the layers have scale.
The current approach:
- add the manipulator visual to the root of the scene https://github.com/napari-threedee/napari-threedee/pull/168/commits/f09616f9636b4a343929fa76b559cdb2d28f08e0
- make the base manipulator use world coordinates: https://github.com/napari-threedee/napari-threedee/pull/168/commits/03b791724a4c0345a50314bec9d3b0863d75619f
- update the point manipulator to use world coordinates: https://github.com/napari-threedee/napari-threedee/pull/168/commits/3d54cadfe546f7bf3b95e34048f0eb7207cfc5b3
- update the render plane manipulator to use world coordinates. needed to add util functions for transforming the normal vector: …
> make manipulators use world coordinates

- src/napari_threedee/manipulators/render_plane_manipulator.py
Closes: https://github.com/napari-threedee/napari-threedee/issues/177
In this PR I flip the normal for the render plane manipulator.
If you use the script from the issue, you just need to tilt the camera down a smidge to be able to use the manipulator in an intuitive fashion:
> [UX] flip the render plane manipulator normal

- .github/workflows/test_and_deploy.yml
- tox.ini
(not sure why I wrote 3.12 in the commit...we'll want that sooner rather than later though too I guess)
This PR adds python 3.11 to the test matrix.
Also may want to consider dropping 3.8 soon-ish. 
napari dropped testing for 3.8 (and added 3.12) here: https://github.com/napari/napari/pull/6738
> [Maint] test on python 3.11

- src/napari_threedee/manipulators/base_manipulator.py
Closes: https://github.com/napari-threedee/napari-threedee/issues/175
I think this is the correct fix? calling the `_on_transformation_changed()` method `_on_enable`?
> Bugfix: update transformations on_enable

- src/napari_threedee/_backend/manipulator/_tests/test_manipulator.py
- src/napari_threedee/_backend/manipulator/napari_manipulator_backend.py
- src/napari_threedee/manipulators/base_manipulator.py
Closes: https://github.com/napari-threedee/napari-threedee/issues/183
In this PR I connect the dims.ndisplay event to `_on_ndisplay_changed` in base_manipulator init.
Then, in `_on_ndisplay_changed` I change the node.order so that the manipulator is properly restored when toggling back to 3D.
This fixes the issue.
Question:
There is another unconnected callback here:
https://github.com/napari-threedee/napari-threedee/blob/fdfac7246d18bb72dc5ec3c0989a4c6b252b14a7/src/napari_threedee/_backend/manipulator/napari_manipulator_backend.py#L202-L206
Would the node.order be better there? Should I connect that one instead?
Or should that be removed? The mouse/drag callbacks are handled in base_manipulator:
https://github.com/napari-threedee/napari-threedee/blob/fdfac7246d18bb72dc5ec3c0989a4c6b252b14 …
> [bugfix] connect to ndisplay change and set node.order

- src/napari_threedee/_backend/manipulator/_tests/test_manipulator.py
- src/napari_threedee/manipulators/render_plane_manipulator.py
Ran into this recently:
If you have a 3D layer in plane mode with a render plane manipulator and you switch the 3d display depiction from plane to volume, the render plane manipulator persists inside the volume. 
It's wierd and not really what I would expect.
With this PR I connect to the depiction event and disable the manipulator in volume view. It comes back when you switch back to plane.
> [Enh] Disable render plane manipulator if depication switched to volume

- src/napari_threedee/_backend/manipulator/translator.py
- src/napari_threedee/_backend/manipulator/vispy_visual_data.py
Closes: https://github.com/napari-threedee/napari-threedee/issues/179
Alternative to: https://github.com/napari-threedee/napari-threedee/pull/180
So in this PR I eliminate the small gap and put the handle at the *end* of the extra segment.
Here's what it looks like with a bit of zoom -- when zoomed out and the handle Marker covers much of the extra segment.
> fix translator handle position and segment

- .github/workflows/test_and_deploy.yml
Github actions moved `macos-latest` to arm. Temporary fix based on  https://github.com/napari/napari/pull/6858
> update MacOS version in Actions

- setup.cfg
I'm trying to figure out why conda-forge feedstock isn't getting any updates.
In the process I noticed the conda-forge bot commenting on missing dependencies in the recipe. Sure enough, they are missing in setup.cfg. Everything works because they are napari requirements, but I think everything that is imported in this codebase should be in setup.cfg.
Note I removed npe2, my understanding is that plugins don't depend on/use it.
> [maint] ensure all imports are in install_requires

- src/napari_threedee/_backend/manipulator/_tests/test_manipulator.py
- src/napari_threedee/_backend/manipulator/rotator.py
- src/napari_threedee/_backend/manipulator/translator.py
- src/napari_threedee/_backend/manipulator/vispy_visual_data.py
- src/napari_threedee/manipulators/base_manipulator.py
This is based off of Kevin's thoughts here: https://github.com/napari-threedee/napari-threedee/issues/163#issuecomment-2053562968
I implemented the radius property to control the size of the manipulator.
Then in analogous fashion added handle_size.
Now I'm not sure about the latter -- I guess the handle sizes are vispy marker sizes which are in screen/scene space? so not affected by scale? Maybe unneeded, but still sometimes can be handy.
Note: right now it's just properties and setter, not in the widgets. I'd like to be sure this is working properly and then do widgets in a followup PR?
> Enhancement: add radius and handle_size as a properties of base_manipulator

- src/napari_threedee/_backend/manipulator/napari_manipulator_backend.py
Closes: https://github.com/napari-threedee/napari-threedee/issues/192
So previously it worked because translators had a scalar `handle_size`. But after changes to make setters, handle_size is an array. Now all the handle_size for rotators and translators are set together, to the same value, so which element you use doesn't matter, as long as a scalar is passed as `sphere_diameter`.
This is not the most elegant way of solving this. But I don't think can access BaseManipulator.radius here...
One could pass the arrays of handle_size instead of constructing an array of sphere_diameter in `select_sphere_from_click`? But that's a bigger refactor probably to ensure it doesn't break something else.
> [bugfix] pass scalar sphere_diameter value from handle_size array

- src/napari_threedee/napari.yaml
Closes: https://github.com/napari-threedee/napari-threedee/issues/134
I also ran into the issue where the (non-existent) writer was the default for Points.
The `io` module was removed in https://github.com/napari-threedee/napari-threedee/pull/96
But the reader/writer remain in the manifest.
In this PR i comment out the contributions in case in the future we want to put them back.
> [bugfix] remove non-existent writer and reader contributions

- src/napari_threedee/_backend/manipulator/napari_manipulator_backend.py
- src/napari_threedee/manipulators/base_manipulator.py
Closes https://github.com/napari-threedee/napari-threedee/issues/195
In this PR I try to disconnect events when the layer is removed.
It resolves the issue, but I'm not sure if it's sufficient/complete teardown.
> bugfix: disconnect events when layer is removed.

- src/napari_threedee/_backend/manipulator/manipulator_model.py
napari-threedee doesn't pin back pydantic, but morphosamplers does.
In working on lifting the pin in morphosamplers, I got validation errors when running tests here with pydantic v2, e.g.:
```
_______________________________________ test_instantiation _______________________________________
def test_instantiation():
>       manipulator = ManipulatorModel(
central_axes='xyz',
translators='xy',
rotators='z',
)
src/napari_threedee/_backend/manipulator/_tests/test_manipulator.py:8: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
_model_self_ = ManipulatorModel()
data = {'central_axes': 'xyz', 'rotators': 'z', 'translators': 'xy'}
def __init__(_model_self_, **data: Any) -> None:
>       super().__init__(**data)
E …
```
> [pydantic2] make optional optional

- src/napari_threedee/utils/selection_utils.py
Closes: https://github.com/napari-threedee/napari-threedee/issues/196
This PR will make every value of `handle_size` work as long as it's non-zero.
The click radius includes the border now.
> bugfix: use handle_size/2 for the in_slice_matches

- mkdocs.yml
Closes: https://github.com/napari-threedee/napari-threedee/issues/213
This should put in a copy button for code cells, per mkdocs-material docs:
https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button
> [Docs] Update mkdocs.yml to add copy button to code cells

- src/napari_threedee/annotators/points/annotator.py
Closes #194 
Alternative to https://github.com/napari-threedee/napari-threedee/pull/201
In the other PR we determined that manipulators work because they use layer mouse events not viewer ones
https://github.com/napari-threedee/napari-threedee/pull/201#issuecomment-2108806063
I noticed that labels annotator also uses layer events:
https://github.com/napari-threedee/napari-threedee/blob/8fbe1631d3f16c90e33560ed053d5ea2045c94fb/src/napari_threedee/annotators/label/annotator.py#L53-L56
So this PR implements that strategy for the points annotator.
> Use layer mouse callback for points annotator

- docs/tutorials/segmentation_tutorial.md
Closes https://github.com/napari-threedee/napari-threedee/issues/214
In this PR I address the problems noted in the issue:
1. I update the installation instructions:
- clarify conda/mamba slightly
- use conda-forge explicitly
- install everything using mamba/conda, without mixing in pip
- ensure pyqt and napari-threedee are installed
- ensure linux ocl wrapper install command is provided
2. make small changes to the copy, fixing menu names, making them bold, and updating labels in the apoc widget.
> [Docs] Update segmentation tutorial installation instructions and some copy

- docs/examples/plugin/sphere_annotator_plugin.py
- docs/how_to/sphere_annotator.md
Closes: https://github.com/napari-threedee/napari-threedee/issues/209
In this PR I remove the extra, spurious layer from the script and rename the orange one to match the docs.
The points and surface layer names are default names, so I just note that they may differ from the screenshots/videos and clarify the copy.
Additionally, as with the other How tos, I add instructions for downloading and running the example.
> [Docs] Fix How To 5, sphere annotator

- docs/how_to/render_plane_manipulator.md
- src/napari_threedee/napari.yaml
Closes: https://github.com/napari-threedee/napari-threedee/issues/205
In the PR I correct the napari.yaml display name of the sample to be consistent and do minor copy-edits to the text:
1. provide a link to Zenodo
2. warn about sample file size
3. warn that there may be subtle visual differences depending on versions of n3d and napari
4. specify that double-click moves the manipulator (that is the actual napari shortcut, shift-click working is technically a bug? see https://github.com/napari/napari/blob/main/napari/layers/image/_image_mouse_bindings.py )
> [Docs] update How To 1 (render plane manipulator)

- docs/examples/library/point_annotator_library.py
- src/napari_threedee/annotators/paths/annotator.py
- src/napari_threedee/annotators/points/annotator.py
- src/napari_threedee/annotators/spheres/annotator.py
- src/napari_threedee/annotators/surfaces/annotator.py
- src/napari_threedee/utils/_tests/test_mouse_callbacks.py
- src/napari_threedee/utils/mouse_callbacks.py
- src/napari_threedee/utils/napari_utils.py
this PR adds the ability to add points onto planes with the 'a' key in addition to the existing alt + click behavior
two reasons:
- I found myself in a desktop environment where alt clicking didn't work
- it's easier to be precise when using a trackpad
@kevinyamauchi @psobolewskiPhD what do you think? I'd like to get this in as it's stopping me from using n3d in our virtual desktops here
> add 'add point on key press' functionality

- docs/dev_guides/manipulators.md
In this PR I try to update the manipulator explanation, under explanations.
I document
- the change in coordinate systems: manipulators use world coordinates now
- the added `radius` and `handle_size` properties to change the size in world coord
- try to update the implementation description
> [Docs] Update Explanations: manipulator explanation

- docs/dev_guides/core_concepts.md
In this PR I've replaced the outdated graphic with the new one and tweaked the copy to highlight the differences between translator and rotator handles.
> [Docs] Update core_concepts.md with new manipulator graphic

- src/napari_threedee/manipulators/layer_manipulator.py
This print leaked in via https://github.com/napari-threedee/napari-threedee/pull/168/files#diff-d6de47217f7a11c7748d0951b735668702bfd7d6ed7f4f6ad764b0074de8bc07
It's not informative nor really needed, so I suggest deleting.
> [Maint] remove spurious print in layer_manipulator

- src/napari_threedee/manipulators/constants.py
Closes https://github.com/napari-threedee/napari-threedee/issues/240
I think as long as the binding is just a simple character, we can safely use a string, which will work in 0.4.19 and 0.5.0
> [Bugfix, napari 0.5.0] Just use string `a` as the keybinding for adding a point

- setup.cfg
napari[all] intalls pyqt5, but napari can use other Qt backends
Currently, if a developer has a different Qt backend installed (e.g. PyQt6, which as of 0.5.0a is no longer an experimental backend) and installs the dev installation of napari-threedee they will get an extra Qt backend which can cause major issues in the environment.
Note: trying to launch napari without a Qt backend gives a reasonably informative message.
> Update setup.cfg: remove napari[all] from dev

- requirements.txt
This PR fixes broken docs workflow due to https://github.com/napari-threedee/napari-threedee/pull/245
https://github.com/napari-threedee/napari-threedee/actions/runs/9798343315/job/27056705375
Docs build used a pure [dev] install, so it's missing pyqt5:
https://github.com/psobolewskiPhD/napari-threedee/blob/ee4c0739b513395d16f84b6df27119173dbb1d91/.github/workflows/test_and_deploy.yml#L83
tests work because tox.ini specifies pyqt5:
https://github.com/napari-threedee/napari-threedee/blob/4286c63a9dd13c6352ef2217c71ff0c7598609ad/tox.ini#L30-L38
So in this PR i add pyqt5 to the docs requirements.txt
> Update requirements.txt to include pyqt5

- src/napari_threedee/annotators/dipoles/annotator.py
- src/napari_threedee/data_models/dipoles.py
- src/napari_threedee/utils/_tests/test_mouse_callbacks.py
- src/napari_threedee/visualization/_tests/test_lighting_control.py
this test passed on napari 0.4.19 but failed on 0.5.0
I think there were expectations in this test that I'm not sure should work - that you can annotate into a points layer with an arbitrary transform
Here I modify the test so that the layer you are annotating can have the arbitrary scale, but the points will be in world coordinates
> fix tests for napari 0.5.0

- src/napari_threedee/annotators/dipoles/annotator.py
A small addition to skip when vector norm is 0 so that there are no errors while drawing the vector in tomoslice
> Correction for 0 dipole vector norm

- .github/workflows/test_and_deploy.yml
codecov on macos is causing failures... 
https://github.com/napari-threedee/napari-threedee/actions/runs/10924809433
this is blocking deployment so temporarily disabling
> don't run codecov on macos right now

- setup.cfg
On py3.11 we're getting zarr v3 and the n3d implementations doesn't support it, so all the zarr related tests are failing.
Other things do work fine though.
Anyhow, to fix CI, I suggest using <3 for zarr for the time being.
Note a lot of the ecosystem doesn't support it, including ome-zarr-py:
https://github.com/ome/ome-zarr-py/blob/efe0391202000b5bd7e0c8ef6f07cc0481f35fc8/pyproject.toml#L22
> Fix tests on py3.11+: Update setup.cfg to block zarr >3

- mkdocs.yml
Doc builds are failing:
https://github.com/napari-threedee/napari-threedee/actions/runs/14581832216/job/40900145038
I think I have things updated correctly for the newer version of mkdocs/mkdocstrings
> [maint] Update mkdocs.yml to try to fix docs build
