examples/points_manipulator.py
src/napari_threedee/manipulators/base_manipulator.py
src/napari_threedee/manipulators/point_manipulator.py
src/napari_threedee/utils/napari_utils.py

This PR adds visibility to manipulators and selection to the PointManipulator.

Add visibility to manipulators and selection to PointManipulator

---

docs/_config.yml
docs/_toc.yml
docs/api/api.rst
docs/dev_guides/dev_guides.md
docs/dev_guides/manipulators.md
docs/how_to/how_to.md
docs/index.md
docs/tutorials/tutorials.md
setup.cfg
src/napari_threedee/manipulators/base_manipulator.py
src/napari_threedee/manipulators/layer_manipulator.py
src/napari_threedee/manipulators/render_plane_manipulator.py

This PR adds some initial docs that we can build using jupyterbook.

[WIP] Init docs

---

src/napari_threedee/manipulators/base_manipulator.py

fixes a few errors from when static analysis was broken in the base manipulator

Fix base manipulator

---

docs/dev_guides/manipulators.md
src/napari_threedee/manipulators/base_manipulator.py
src/napari_threedee/manipulators/layer_manipulator.py
src/napari_threedee/manipulators/point_manipulator.py
src/napari_threedee/manipulators/render_plane_manipulator.py

fixes inconsistencies in drag callback nomenclature and closes #11

Fix drag name consistency

---

docs/dev_guides/manipulators.md
src/napari_threedee/manipulators/base_manipulator.py
src/napari_threedee/manipulators/point_manipulator.py
src/napari_threedee/manipulators/render_plane_manipulator.py

refactor manipulator centroid -> translation

---

docs/dev_guides/manipulators.md

closes #12 - uses nomenclature from #14

add notes on implementing rotators

---

examples/plane_point_annotator.py
src/napari_threedee/annotators/__init__.py
src/napari_threedee/annotators/plane_point_annotator.py
src/napari_threedee/manipulators/base_manipulator.py
src/napari_threedee/manipulators/point_manipulator.py
src/napari_threedee/utils/napari_utils.py

this PR adds a simple point annotator and includes a slight refactor of the safe add/remove callback functions
https://user-images.githubusercontent.com/7307488/152600988-b6a23817-52c4-4fcf-9ed3-b239efba3564.mp4
things to add
- update so that this works with layer transforms (already done properly elsewhere, just need to find the code)
- configurable modifier key (currently hard coded to 'Alt')

Point annotator

---

examples/plane_point_annotator_widget.py
src/napari_threedee/annotators/plane_point_annotator.py
src/napari_threedee/annotators/qt_plane_point_annotator.py

This PR adds a widget for the plane point annotator which allows you to select layers and enable/disable annotation

Plane point annotator widget

---

.github/workflows/build-and-deploy-docs.yml

sets docs to deploy to napari-threedee.github.io

deploy to base pages

---

.github/workflows/test_and_deploy.yml
README.md
examples/plugin/plane_point_annotator.py
src/napari_threedee/_tests/conftest.py
src/napari_threedee/_tests/test_mouse_callbacks.py
src/napari_threedee/annotators/_tests/test_plane_point_annotator.py
src/napari_threedee/annotators/plane_point_annotator.py
src/napari_threedee/conftest.py
src/napari_threedee/mouse_callbacks.py
src/napari_threedee/utils/selection_utils.py

This PR makes our plane point annotator compatible with nD data
The only restriction at the minute is that the points and image layers must have the same dimensionality

nd-ify the plane point annotator

---

setup.cfg

Pin imageio dependency to fix: https://github.com/napari/napari/pull/5168

fix imageio dependency

---

setup.cfg

update  pypi  python classifiers

---

docs/annotations/io.md
docs/annotations/specifications.md
docs/annotations/spline_spec.md
mkdocs.yml
setup.cfg
src/napari_threedee/annotators/_tests/test_spline_annotator.py
src/napari_threedee/annotators/io/__init__.py
src/napari_threedee/annotators/io/_tests/test_spline.py
src/napari_threedee/annotators/io/constants.py
src/napari_threedee/annotators/io/spline.py
src/napari_threedee/annotators/spline_annotator.py
src/napari_threedee/visualization/_tests/test_camera_spline.py
src/napari_threedee/visualization/camera_spline.py

Hey @kevinyamauchi - I think this is good to go, let me know what you think of the outline for the spec in the docs and if you think anything is missing
Once this is in I will implement a single io plugin entry point in a separate plugin rather than implementing one for every annotator

add specification docs, spline layer spec and functions for spline io

---

mkdocs.yml

make it so the subsections in the docs nav are hidden behind an expand.

make nav have expands

---

examples/library/surface_annotator.py
setup.cfg
src/napari_threedee/annotators/_qt/__init__.py
src/napari_threedee/annotators/_qt/qt_surface_annotator.py
src/napari_threedee/annotators/surface_annotator.py

Near clone of the spline annotator, uses morphometrics/morphosamplers#7 - works pretty well! Some issues with mesh generation reported in morphometrics/morphosamplers#15
https://user-images.githubusercontent.com/7307488/213765969-94ad1f99-8cd5-4e02-974d-8d49d1b26104.mp4

[WIP] surface annotator

---

src/napari_threedee/annotators/sphere_annotator.py

- ensure surface layer is added to the layerlist if not present
- don't require an image layer for points layer creation

minor fixes to the SphereAnnotator

---

src/napari_threedee/data_models/_tests/test_points.py
src/napari_threedee/data_models/points.py

force points to be 3D if 0D

---

src/napari_threedee/annotators/paths/annotator.py

bugfix - need to add some tests for the annotators too

fix path color generation

---

src/napari_threedee/data_models/paths.py

This PR makes the path annotator automatically select the last path when instantiated from existing data via the Path data model

select last point during layer creation

---

docs/examples/plugin/ambient_occlusion_plugin.py
docs/how_to/ambient_occlusion.md
mkdocs.yml
src/napari_threedee/visualization/_qt/qt_lighting_control.py

adds an example for the ambient occlusion plugin and a how to in the docs.

Add ambient occlusion example and how to

---

.github/workflows/test_and_deploy.yml
src/napari_threedee/_tests/test_dock_widget.py
src/napari_threedee/_tests/test_mouse_callbacks.py
src/napari_threedee/annotators/__init__.py
src/napari_threedee/annotators/_qt/__init__.py
src/napari_threedee/annotators/_qt/qt_label_annotator.py
src/napari_threedee/annotators/_tests/test_plane_labeler.py
src/napari_threedee/annotators/label/__init__.py
src/napari_threedee/annotators/label/annotator.py
src/napari_threedee/conftest.py
src/napari_threedee/dock_widgets.py
src/napari_threedee/napari.yaml

This PR adds an annotator for painting labels on a rendering plane.
Based on: https://github.com/napari/napari/pull/4346 by @alisterburt 
https://github.com/napari-threedee/napari-threedee/assets/1120672/5cd902aa-df30-426a-92c7-3ecae70c9027

Plane label annotator

---

src/napari_threedee/utils/_tests/test_geometry.py
src/napari_threedee/utils/geometry.py

fixes what I think I understood from #136

Make points on edge of bounding box count as inside

---

docs/tutorials/segmentation_tutorial.md
mkdocs.yml
src/napari_threedee/annotators/label/annotator.py

this PR adds a step-by-step tutorial for annotating labels on planes

add annotation tutorial

---

src/napari_threedee/utils/selection_utils.py

Closes: https://github.com/napari-threedee/napari-threedee/issues/173
This PR implements the math fix from Alister:
https://github.com/napari-threedee/napari-threedee/issues/173#issuecomment-2067650669

[bugfix] Handle selection math fix from Alister

---

setup.cfg
src/napari_threedee/_sample_data.py
src/napari_threedee/napari.yaml

As discussed in https://github.com/napari-threedee/napari-threedee/issues/205, this PR adds the HIV particle sample data plugin.

add hiv sample data plugin

---

docs/examples/plugin/point_annotator_plugin.py
docs/how_to/point_annotator.md

Closes: https://github.com/napari-threedee/napari-threedee/issues/208
In this PR I fix the script to ensure that a Points layer is present, so that the annotation works.
I also clarify the copy regarding downloading and running the script and that there may be subtle visual differences depending on n3d/napari version. Finally, I add some minor clarifications related to the feature.

[Docs] Update How To 4, points annotation

---

docs/how_to/layer_manipulator.md

Closes: https://github.com/napari-threedee/napari-threedee/issues/207
This PR updates the copy of the How To to describe how to download and run the script and then warns that there may be subtle visual differences depending on n3d and napari versions.

[Docs] Update How to 3, layer manipulator

---

docs/how_to/point_manipulator.md

Closes: https://github.com/napari-threedee/napari-threedee/issues/206
In this PR I provide instructions how to download and run the example script and then update the copy a bit to account for the fact that the widget is already showing.

[Docs] Update How to 2, points manipulator

---

docs/how_to/point_annotator.md

Docs update for: https://github.com/napari-threedee/napari-threedee/pull/227

[Docs] Update point_annotator.md for `a` key binding

---

src/napari_threedee/manipulators/render_plane_manipulator.py

cc @psobolewskiPhD this is a slightly more robust implementation of what you wanted in #178
https://github.com/napari-threedee/napari-threedee/assets/7307488/18b173e9-44ba-46de-8d96-b910baf2fb19

have the manipulator always point up

---

docs/examples/library/dipole_annotator_library.py
src/napari_threedee/annotators/__init__.py
src/napari_threedee/annotators/dipoles/__init__.py
src/napari_threedee/annotators/dipoles/annotator.py
src/napari_threedee/annotators/dipoles/constants.py
src/napari_threedee/data_models/__init__.py
src/napari_threedee/data_models/dipoles.py

Interactively adding and editing dipoles with dipole annotator 
:partying_face: 
[recording_dipole_annotator.webm](https://github.com/napari-threedee/napari-threedee/assets/150450168/722aa0f5-7feb-42a5-96e1-96d84932439b)

Add implementation of dipole annotator

---

docs/examples/library/dipole_annotator_library.py
src/napari_threedee/annotators/dipoles/annotator.py
src/napari_threedee/data_models/dipoles.py

Hi @alisterburt, these are the small corrections for the dipoles I mentioned before: for the empty layer creation correction and typo in the example

Corrections for dipoles

---

.github/workflows/test_and_deploy.yml
docs/tutorials/segmentation_tutorial.md
pyproject.toml
tox.ini

Make sure pyproject and tox are synced. Also use 311 for docs instead of 39.

Add 313 and drop 39 in tox and docs and pyproject
